export const NAV_ITEMS = [
  "Dashboard", "Bill Payments", "Corporate Travel", "Payroll",
  "Office Supplies", "Softwares", "Logistics", "Gift Cards",
  "Marketplace", "Tax & More", "Accounting", "Invoicing",
  "Insurance", "Corporate Cards", "Hub", "WhatsApp for Business",
  "Co Founder", "More Services",
];

export const FOOTER_LINKS = [
  "Peko Platform Agreement", "Privacy Policy", "Refund Policy", "Cookie Policy",
];

export const CATEGORIES = [
  {
    id: "general",
    name: "General / Commercial Contracts",
    icon: "📋",
    bg: "#F0F4FF",
    docs: [
      "Non-Disclosure Agreement (NDA) – Mutual",
      "Non-Disclosure Agreement (NDA) – One-Way",
      "Non-Compete Agreement",
      "Non-Solicitation Agreement",
      "Master Services Agreement (MSA)",
      "Service Agreement",
      "Consultancy Agreement",
      "Freelance Agreement",
      "Vendor Agreement",
      "Supply Agreement",
      "Distribution Agreement",
      "Licensing Agreement (IP / Software)",
      "Franchise Agreement",
      "Joint Venture Agreement",
      "Memorandum of Understanding (MoU)",
      "Terms & Conditions (Website/App)",
      "Privacy Policy",
      "Refund & Cancellation Policy",
      "Influencer / Marketing Agreement",
    ],
  },
  {
    id: "corporate",
    name: "Corporate / Start-up / Investment",
    icon: "🏢",
    bg: "#F5F3FF",
    docs: [
      "Shareholders' Agreement (SHA)",
      "Share Subscription Agreement (SSA)",
      "Founders' Agreement",
      "ESOP Policy & Grant Letter",
      "Board Resolution Template",
      "Share Transfer Agreement",
      "Term Sheet (Investment)",
      "Partnership Deed",
      "LLP Agreement",
    ],
  },
  {
    id: "employment",
    name: "Employment & HR",
    icon: "👥",
    bg: "#F0FFF4",
    docs: [
      "Employment Agreement",
      "Offer Letter",
      "Independent Contractor Agreement",
      "Confidentiality Agreement",
      "Non-Solicitation and Non-Compete Agreement",
      "HR Policy Manual",
      "Code of Conduct",
      "Sexual Harassment (POSH) Policy",
      "Termination Letter (With Cause)",
      "Termination Letter (Without Cause)",
      "Resignation Acceptance Letter",
      "Experience Letter",
      "Full & Final Settlement Letter",
    ],
  },
  {
    id: "realestate",
    name: "Real Estate & Property",
    icon: "🏠",
    bg: "#FFF7ED",
    docs: [
      "Lease Agreement (Residential)",
      "Commercial Lease Deed",
      "Rent Agreement",
      "Leave & License Agreement",
      "Eviction Notice",
      "Rent Demand Notice",
      "Sale Agreement (Property)",
      "Sale Deed",
      "Gift Deed",
      "Power of Attorney (Property)",
      "Builder-Buyer Agreement",
      "Allotment Letter",
      "Possession Letter",
    ],
  },
  {
    id: "litigation",
    name: "Litigation & Court Documents",
    icon: "⚖️",
    bg: "#FFF0F0",
    docs: [
      "Suit for Recovery",
      "Written Statement",
      "Legal Notice (General)",
      "Legal Notice (Recovery)",
      "Reply to Legal Notice",
      "Affidavit",
      "Injunction Application",
      "Execution Petition",
      "Writ Petition (Article 226)",
      "Writ Petition (Article 32)",
      "Special Leave Petition (SLP)",
      "Review Petition",
      "Criminal Complaint",
      "FIR Draft",
      "Bail Application (Regular)",
      "Bail Application (Anticipatory)",
      "Quashing Petition (Section 482 CrPC)",
    ],
  },
  {
    id: "family",
    name: "Family Law",
    icon: "👨‍👩‍👧",
    bg: "#FDF0FF",
    docs: [
      "Mutual Divorce Petition",
      "Contested Divorce Petition",
      "Child Custody Petition",
      "Maintenance Petition",
      "Domestic Violence Complaint",
      "Separation Agreement",
    ],
  },
  {
    id: "banking",
    name: "Banking / Finance / Recovery",
    icon: "🏦",
    bg: "#F0FFF4",
    docs: [
      "Loan Agreement",
      "Promissory Note",
      "Personal Guarantee Agreement",
      "Demand Notice for Recovery",
      "Settlement Agreement",
    ],
  },
  {
    id: "ip",
    name: "Intellectual Property (IP)",
    icon: "💡",
    bg: "#FFFBEB",
    docs: [
      "Trademark License Agreement",
      "IP Assignment Agreement",
      "IP License Agreement",
      "Cease & Desist Notice",
    ],
  },
  {
    id: "ecommerce",
    name: "E-commerce / Tech / Platform",
    icon: "💻",
    bg: "#F0F4FF",
    docs: [
      "Seller Agreement (Marketplace)",
      "Vendor Onboarding Agreement",
      "SaaS Agreement",
      "API Integration Agreement",
      "Data Processing Agreement (DPDP Compliant)",
      "Cookie Policy",
      "End User License Agreement (EULA)",
    ],
  },
  {
    id: "notices",
    name: "Notices & Declarations",
    icon: "📢",
    bg: "#FFF7ED",
    docs: [
      "Legal Notice (Recovery / Breach)",
      "Affidavit (Name Change)",
      "Affidavit (Address Proof)",
      "Indemnity Bond",
      "Declaration Letter",
      "Authority Letter",
      "Board Declaration",
      "Consent Letter",
    ],
  },
  {
    id: "misc",
    name: "Miscellaneous",
    icon: "📁",
    bg: "#F3F4F6",
    docs: [
      "Power of Attorney (General)",
      "Will",
      "Trust Deed",
      "Arbitration Agreement",
    ],
  },
];
