export const NAV_ITEMS = [
  "Dashboard", "Bill Payments", "Corporate Travel", "Payroll",
  "Office Supplies", "Softwares", "Logistics", "Gift Cards",
  "Marketplace", "Tax & More", "Accounting", "Invoicing",
  "Insurance", "Corporate Cards", "Hub", "WhatsApp for Business",
  "Co Founder", "More Services",
];

export const FOOTER_LINKS = [
  "Peko Platform Agreement", "Privacy Policy", "Refund Policy", "Cookie Policy",
];

export const CATEGORIES = [
  {
    id: "general",
    name: "General / Commercial Contracts",
    icon: "📋",
    bg: "#F0F4FF",
    docs: [
      "Non-Disclosure Agreement (NDA) - Mutual",
      "Non-Disclosure Agreement (NDA) - One-Way",
      "Non-Compete Agreement",
      "Non-Solicitation Agreement",
      "Master Services Agreement (MSA)",
      "Service Agreement",
      "Consultancy Agreement",
      "Freelance Agreement",
      "Vendor Agreement",
      "Supply Agreement",
      "Distribution Agreement",
      "Licensing Agreement (IP / Software)",
      "Franchise Agreement",
      "Joint Venture Agreement",
      "Memorandum of Understanding (MoU)",
      "Terms & Conditions (Website/App)",
      "Privacy Policy",
      "Refund & Cancellation Policy",
      "Influencer / Marketing Agreement",
    ],
  },
  {
    id: "corporate",
    name: "Corporate / Start-up / Investment",
    icon: "🏢",
    bg: "#F5F3FF",
    docs: [
      "Shareholders Agreement (SHA)",
      "Share Subscription Agreement (SSA)",
      "Founders Agreement",
      "ESOP Policy & Grant Letter",
      "Board Resolution Template",
      "Share Transfer Agreement",
      "Term Sheet (Investment)",
      "Partnership Deed",
      "LLP Agreement",
    ],
  },
  {
    id: "employment",
    name: "Employment & HR",
    icon: "👥",
    bg: "#F0FFF4",
    docs: [
      "Employment Agreement",
      "Offer Letter",
      "Independent Contractor Agreement",
      "Confidentiality Agreement",
      "Non-Solicitation and Non-Compete Agreement",
      "HR Policy Manual",
      "Code of Conduct",
      "Sexual Harassment (POSH) Policy",
      "Termination Letter (With Cause)",
      "Termination Letter (Without Cause)",
      "Resignation Acceptance Letter",
      "Experience Letter",
      "Full & Final Settlement Letter",
    ],
  },
  {
    id: "realestate",
    name: "Real Estate & Property",
    icon: "🏠",
    bg: "#FFF7ED",
    docs: [
      "Lease Agreement (Residential)",
      "Commercial Lease Deed",
      "Rent Agreement",
      "Leave & License Agreement",
      "Eviction Notice",
      "Rent Demand Notice",
      "Sale Agreement (Property)",
      "Sale Deed",
      "Gift Deed",
      "Power of Attorney (Property)",
      "Builder-Buyer Agreement",
      "Allotment Letter",
      "Possession Letter",
    ],
  },
  {
    id: "litigation",
    name: "Litigation & Court Documents",
    icon: "⚖️",
    bg: "#FFF0F0",
    docs: [
      "Suit for Recovery",
      "Written Statement",
      "Legal Notice (General)",
      "Legal Notice (Recovery)",
      "Reply to Legal Notice",
      "Affidavit",
      "Injunction Application",
      "Execution Petition",
      "Writ Petition (Article 226)",
      "Writ Petition (Article 32)",
      "Special Leave Petition (SLP)",
      "Review Petition",
      "Criminal Complaint",
      "FIR Draft",
      "Bail Application (Regular)",
      "Bail Application (Anticipatory)",
      "Quashing Petition (Section 482 CrPC)",
    ],
  },
  {
    id: "family",
    name: "Family Law",
    icon: "👨‍👩‍👧",
    bg: "#FDF0FF",
    docs: [
      "Mutual Divorce Petition",
      "Contested Divorce Petition",
      "Child Custody Petition",
      "Maintenance Petition",
      "Domestic Violence Complaint",
      "Separation Agreement",
    ],
  },
  {
    id: "banking",
    name: "Banking / Finance / Recovery",
    icon: "🏦",
    bg: "#F0FFF4",
    docs: [
      "Loan Agreement",
      "Promissory Note",
      "Personal Guarantee Agreement",
      "Demand Notice for Recovery",
      "Settlement Agreement",
    ],
  },
  {
    id: "ip",
    name: "Intellectual Property (IP)",
    icon: "💡",
    bg: "#FFFBEB",
    docs: [
      "Trademark License Agreement",
      "IP Assignment Agreement",
      "IP License Agreement",
      "Cease & Desist Notice",
    ],
  },
  {
    id: "ecommerce",
    name: "E-commerce / Tech / Platform",
    icon: "💻",
    bg: "#F0F4FF",
    docs: [
      "Seller Agreement (Marketplace)",
      "Vendor Onboarding Agreement",
      "SaaS Agreement",
      "API Integration Agreement",
      "Data Processing Agreement (DPDP Compliant)",
      "Cookie Policy",
      "End User License Agreement (EULA)",
    ],
  },
  {
    id: "notices",
    name: "Notices & Declarations",
    icon: "📢",
    bg: "#FFF7ED",
    docs: [
      "Legal Notice (Recovery / Breach)",
      "Affidavit (Name Change)",
      "Affidavit (Address Proof)",
      "Indemnity Bond",
      "Declaration Letter",
      "Authority Letter",
      "Board Declaration",
      "Consent Letter",
    ],
  },
  {
    id: "misc",
    name: "Miscellaneous",
    icon: "📁",
    bg: "#F3F4F6",
    docs: [
      "Power of Attorney (General)",
      "Will",
      "Trust Deed",
      "Arbitration Agreement",
    ],
  },
];

export const VENDOR_DOC_CONTENT = [
  { type: "title",   text: "VENDOR AGREEMENT" },
  { type: "meta",    text: "This Vendor Agreement (hereinafter referred to as 'Agreement') is made and entered on [insert] day of [insert month], [insert year]." },
  { type: "section", text: "BY AND BETWEEN" },
  { type: "body",    text: "[Insert Company Name], a company incorporated under the laws of [insert Jurisdiction], having its registered office at [insert address] (hereinafter referred to as the 'Client') of the First Part;" },
  { type: "body",    text: "AND" },
  { type: "body",    text: "[Insert Vendor Name], a [insert type of entity], having its office at [insert address] (hereinafter referred to as the 'Vendor') on the Other Part." },
  { type: "body",    text: "The Client and Vendor are hereinafter collectively referred to as the 'Parties' and individually as a 'Party'." },
  { type: "section", text: "WHEREAS" },
  { type: "bullet",  text: "The Client is in the business of [insert brief description of Client]." },
  { type: "bullet",  text: "The Vendor is engaged in the business of providing products and services [insert detailed description]." },
  { type: "bullet",  text: "The Client is desirous of engaging the Vendor as an independent contractor for the provision of such Services." },
  { type: "clause",  num: "1.", text: "Scope of Services" },
  { type: "body",    text: "The Client hereby engages the Vendor to supply the Products and Services described above and as may be further detailed in a separate annexure titled 'Scope of Work' (SOW). Any additional services shall require mutual written agreement." },
  { type: "body",    text: "The Vendor acknowledges and agrees that it shall provide the Services with due skills and diligence and in accordance with the best industry practice and to the satisfaction of the Client." },
  { type: "clause",  num: "2.", text: "Commercials" },
  { type: "body",    text: "The Client agrees to pay a total consideration of [insert] ('Purchase Price') to the Vendor in accordance with the payment terms stipulated in this Agreement. The payments shall be milestones-based and/or delivery-linked, as mutually agreed between the Parties." },
  { type: "clause",  num: "3.", text: "Retention of Title and Transfer of Risk" },
  { type: "body",    text: "Notwithstanding delivery of Service, title in the Service shall remain with the Vendor until full payment is received. Risk passes to the Client upon delivery, regardless of title retention." },
  { type: "clause",  num: "4.", text: "Representations and Warranties" },
  { type: "body",    text: "The Vendor represents and warrants that it has full authority to enter this Agreement; possesses necessary expertise and resources to perform the Services; and all Deliverables shall materially conform to the agreed specifications." },
  { type: "clause",  num: "5.", text: "Indemnity" },
  { type: "body",    text: "Each Party shall indemnify, defend, and hold harmless the other Party from and against any and all losses, damages, liabilities, claims, proceedings, costs, and expenses (including reasonable legal fees)." },
  { type: "clause",  num: "6.", text: "Limitation of Liability" },
  { type: "body",    text: "To the fullest extent permitted by applicable law, neither Party shall be liable for any indirect, incidental, special, punitive, or consequential damages. Aggregate liability shall not exceed total payments received under this Agreement." },
  { type: "clause",  num: "7.", text: "Term and Termination" },
  { type: "body",    text: "This Agreement terminates automatically upon full performance by both Parties. Either Party may terminate immediately upon insolvency of the other Party, or upon material breach not remedied within the notice period." },
  { type: "clause",  num: "8.", text: "Confidentiality" },
  { type: "body",    text: "Each Party agrees not to use or disclose the other Party's Confidential Information without prior written consent. Obligations survive for two (2) years after termination; trade secrets survive indefinitely." },
  { type: "clause",  num: "9.", text: "Governing Law and Jurisdiction" },
  { type: "body",    text: "This Agreement shall be governed by the laws of [insert Jurisdiction]. Each Party irrevocably submits to the exclusive jurisdiction of the courts in [insert City, State]." },
  { type: "sig",     text: "IN WITNESS WHEREOF, the Parties have executed this Agreement on the date first mentioned above." },
];
